[COE-446] Feature creation for generating alerts in Teams hook
ProjetaAi/mlops-monitor pull request #5
Opened 2023-07-05 21:13 UTC by isabellabarcelossg

2023-07-06 08:30 UTC, thems22g requested changes

2023-07-06 08:30 UTC, ms-cmy commented on mlops/hooks.py
> +        payload = Hooks.generate_payload(title, message, severity)
se está chamando a própria classe dentro dela, generate_payload tem que ser staticmethod?

2023-07-06 08:30 UTC, ms-cmy commented on mlops/hooks.py
> +        teams = pymsteams.connectorcard("link")
como que a classe vai receber o link do weebhook?

2023-07-06 08:30 UTC, ms-cmy commented on mlops/hooks.py
> +        teams.send()
vale apena ver se não tem um context manager para abrir conexão e depois fechar

2023-07-06 08:30 UTC, ms-cmy commented on mlops/hooks.py
> +        title = alert_dict["title"]
não é melhor a função receber explicitamente esses 3 argumentos ao invés de estar em um dict, já que vc vai usar elas separadamente de qualquer maneira?

2023-07-06 18:54 UTC, isabellabarcelossg commented on mlops/hooks.py
> +        teams = pymsteams.connectorcard("link")
decidimos deixar como variável de ambiente

2023-07-10 18:50 UTC, Juanmlops approved these changes, later dismissed

2023-07-11 14:56 UTC, thems22g requested changes

2023-07-11 14:56 UTC, ms-cmy commented on .vscode/settings.json
tomar cuidado, esse arquivo n deveria estar no commit

2023-07-11 14:56 UTC, ms-cmy commented on tests/unit/test_logger.py
editou sem querer?

2023-07-11 14:56 UTC, ms-cmy commented on mlops/hooks.py
> +        try:
esse try except está redundante, se quiser dar logging no erro pode colocar na funcao check_dict:
``` python
if missing_fields:
            error_message = f"Os seguintes campos estão faltando: {', '.join(missing_fields)}"
            logging.error(error_message)
            raise ValueError(error_message)
```

2023-07-11 18:01 UTC, isabellabarcelossg commented on tests/unit/test_logger.py
sim, tava olhando pra comparar e adicionei uma linha

2023-07-12 15:02 UTC, closed without merging